name: TagGPT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0
  - pip:
    - bertopic[spacy]==0.16.1
    - scikit-learn==1.5.2
    - transformers==4.45.1
    - sentence-transformers==3.1.1
    - pandas==2.2.3
    - requests==2.32.3
    - mistralai==1.1.0
    - python-dotenv==1.0.1
    - mistral-common==1.4.4
    - tiktoken==0.7.0